### ISSUE TITLE
Recommendation: Remove Final

### ISSUE THREAD

**Issue by aidan-casey** [atomastic/registry#4]
Hey there! Just wanted to make a quick recommendation to remove the final keyword from the class. It would be very helpful to be able to extend the registry.

For example, consider a configuration management class. This could extend the registry class and provide a load method which would populate the registry with configured values from a JSON file, etc.

Willing to make a pull request if this is functionality you would be willing to consider!

**Comment by Awilum** [comment]
removed in [v3.0.0](https://github.com/atomastic/registry/releases/tag/v3.0.0)
