### ISSUE TITLE
Moving to PHP 7.4.0

### ISSUE THREAD

**Issue by Awilum** [atomastic/registry#6]
Define the application minimum supported PHP version 7.4.0

### What's new in PHP 7.4
https://stitcher.io/blog/new-in-php-74

### PHP Versions Stats - 2020.2 Edition
https://blog.packagist.com/php-versions-stats-2020-2-edition/

**Comment by KarelWintersky** [comment]
Крайне хреновое решение. Не на всех продакшенах есть 7.4, например debian buster имеет по умолчанию PHP 7.3

**Comment by Awilum** [comment]
@KarelWintersky а когда обновляться на PHP 7.4 ? почему бы не поддерживать тогда уже и PHP 5.3 ?

**Comment by KarelWintersky** [comment]
Вот потому и не поддерживать PHP 5.3, потому что End of life семерки закончился полтора года назад.

А поддерживать версию надо пока не закончится Security Support. Как минимум. 

А на самом деле тогда, когда версия станет *реально* несовместима с *актуальной* версией PHP. 

Реально, а не хайпово, понимаете?

Но многие библиотеки, реально используемые, отмечу, библиотеки до сих пор требуют minimal requirement - PHP 5.6

Просто потому что более новые версии PHP для них НЕ НЕОБХОДИМЫ. Желательны, но не необходимы.

А теперь ответьте пожалуйста, что такого появится в PHP 7.4 такого, чего нет в PHP 7.3, но без которого эта библиотека станет ущербным уёбищным устаревшим говнокодом?
